[package]
name = "rust_music_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "*"
scraper = "*"
tokio = { version = "*", features = ["full"] }
